# Jekyll configuration
markdown: kramdown

# MyData
owner:
  name:     Hyun Do Jung
  avatar:   photo.jpg
  bio:      "B.Sc in Computer Engineering"
  email:    hjung35@illinois.edu
  github:
  stackexchange:
  linkedin: https://www.linkedin.com/in/hyun-do-jung-27231358/
  instagram:

#text highlighter로 rouge 이용
#2016.02 이후로 syntax highlihgter는 rouge만 지원 
#pygments 사용불가
highlighter: rouge

#작성한 모든 post를 하나의 페이지에 열거할 수 없으니 
#pagination이 필요하고 몇개의 post 를 하나의 page
#보여줄건지를 설정
paginate: 20 # it will paginate after this number

#언어설정
language: 'en-uk'
#words_per_minute: 200


#google search console에서 사용하는 sitemap.xml 생성시 
#이 url key 값이 조재하지 않으면 sitemap.xml이 
#정상적으로 생성되지 않는다
#또한 disqus(댓글시스템)을 이용하기 위해서도 필요 
#자신의 github page url을 입력 
# githubid.github.io 형식
url: https://hyund0.github.io


# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: 생각과 공부의 눈땡글 자취방
description: 기록및 생각과 기술정리를 위한 나만의 블로그식 자취방
cover: assets/built/images/blog-cover1.jpg
logo: 
logo_dark: 
favicon: assets/built/images/favicon.png
production_url:  https://hyund0.github.io/
source_url:  https://github.com/hyund0/GitHubPageMaker
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,



# Social info

# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter:  # replace by your username
facebook:  # replace by your username

# Disqus
disqus: True
disqus_shortname: devm1ke # replace with your disqus username

# Google Analytics
google_analytics: UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
#plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for building master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False


#github user name
username: hyund0
repo: GitHubPageMaker
branch: master
relative_source: 
destination: ./output/


exclude:
  - README.md
  #- Rakefile
  - Gemfile
  - Gemfile.lock  
  - changelog.md
  - "*.Rmd"
  - assets/css
  - assets/images
  - _posts/angular
  - _posts/et-cetera
  #- _posts/python
  - _posts/typescript
  #-_posts/jekyll
  - _posts/iot
  - _posts/r
  - _posts/economy
  - node_modules
  - vendor
  #- .travis.yml
